In [1]:
import sys
import os
# 获取当前Notebook的绝对路径
notebook_dir = os.path.abspath('')
# 项目根目录是Notebook所在目录的父目录
project_root = os.path.abspath(os.path.join(notebook_dir, "../../.."))
# 将项目根目录添加到sys.path
if project_root not in sys.path:
    sys.path.insert(0, project_root)
# 确认路径是否正确
print("当前工作目录:", os.getcwd())
print("项目根目录:", project_root)
print("sys.path:", sys.path)
from apt.vendor.tspro.base import base as base
from apt.os.minio.MinioHandler import MinioClientWrapper

# 创建客户端
minio_client = MinioClientWrapper()

当前工作目录: c:\Users\george\source\repos\MyFunds\jupyterbook\os\minio
项目根目录: c:\Users\george\source\repos\MyFunds
sys.path: ['c:\\Users\\george\\source\\repos\\MyFunds', 'c:\\Users\\george\\anaconda3\\envs\\conda_myfund\\python311.zip', 'c:\\Users\\george\\anaconda3\\envs\\conda_myfund\\DLLs', 'c:\\Users\\george\\anaconda3\\envs\\conda_myfund\\Lib', 'c:\\Users\\george\\anaconda3\\envs\\conda_myfund', '', 'c:\\Users\\george\\anaconda3\\envs\\conda_myfund\\Lib\\site-packages', 'c:\\Users\\george\\anaconda3\\envs\\conda_myfund\\Lib\\site-packages\\ta_lib-0.4.28-py3.11-win-amd64.egg', 'c:\\Users\\george\\anaconda3\\envs\\conda_myfund\\Lib\\site-packages\\win32', 'c:\\Users\\george\\anaconda3\\envs\\conda_myfund\\Lib\\site-packages\\win32\\lib', 'c:\\Users\\george\\anaconda3\\envs\\conda_myfund\\Lib\\site-packages\\Pythonwin', 'c:\\Users\\george\\anaconda3\\envs\\conda_myfund\\Lib\\site-packages\\setuptools\\_vendor']

In [3]:
# 列出所有的桶及其信息
minio_client.list_buckets()

     桶名称              创建日期  总文件数      总大小
0   hdf5  2024-12-19 05:48  5254  80.7 GB
1  share  2024-12-19 05:49     0    0.0 B

In [6]:
# 新建和删除桶
bucket_name = "test"
minio_client.create_bucket(bucket_name)
print("创建桶后:")
print(minio_client.list_buckets())

minio_client.delete_bucket(bucket_name)
print("删除桶后:")
print(minio_client.list_buckets())

创建桶后:
     桶名称              创建日期  总文件数      总大小
0   hdf5  2024-12-19 05:48  5254  80.7 GB
1  share  2024-12-19 05:49     0    0.0 B
2   test  2025-02-24 16:20     0    0.0 B
删除桶后:
     桶名称              创建日期  总文件数      总大小
0   hdf5  2024-12-19 05:48  5254  80.7 GB
1  share  2024-12-19 05:49     0    0.0 B

In [2]:
# 列出桶的文件列表
bucket_name = "hdf5"
# 列出某一个或多个文件 使用prefix做过滤
#minio_client.list_files(bucket_name,prefix="akshare/data/1min/000001.SZ.h5")
# 列出全部文件
minio_client.list_files(bucket_name)

                                          文件名称                 修改日期    文件大小
0               akshare/data/1min/000001.SZ.h5  2024-12-24 12:29:25  31.6MB
1               akshare/data/1min/000002.SZ.h5  2024-12-24 12:29:30  31.1MB
2               akshare/data/1min/000004.SZ.h5  2024-12-24 12:29:24  22.0MB
3               akshare/data/1min/000005.SZ.h5  2024-12-24 12:29:23  22.4MB
4               akshare/data/1min/000006.SZ.h5  2024-12-24 12:29:27  28.9MB
...                                        ...                  ...     ...
5249       akshare/data/1min_test/000008.SZ.h5  2024-12-24 13:13:17  21.8MB
5250       akshare/data/1min_test/000009.SZ.h5  2024-12-24 13:13:19  31.2MB
5251       akshare/data/1min_test/000010.SZ.h5  2024-12-24 13:13:20  19.5MB
5252  akshare/data/1min_test/600000_test.SH.h5  2025-01-08 16:08:18  30.6MB
5253      akshare/data/1min_test/onenote操作.txt  2025-01-05 12:24:22  216.0B

[5254 rows x 3 columns]

In [ ]:
# 上传文件
import tkinter as tk
from tkinter import filedialog
bucket_name = "share"
# 创建一个隐藏的Tkinter窗口
root = tk.Tk()
root.withdraw()
# 弹出文件选择对话框
file_path = filedialog.askopenfilename()
file_name = os.path.basename(file_path)
# 上传文件到Minio
if file_path:
    minio_client.upload_file(bucket_name,file_name, file_path)
    print(f"文件 {file_path} 已上传到桶 {bucket_name}")
else:
    print("未选择文件")

文件 C:/Users/george/Documents/乔治U盘/qzx3(2)/qzx(1)/(1)/PPT/青花瓷（2024.4.25）(小报).pptx 已上传到桶 share